### ISSUE TITLE
Pydantic dep version

### ISSUE THREAD

**Issue by chapati** [vellum-ai/vellum-python-sdks#7] opened 2023-08-31 13:23 UTC
Currently vellum client depends on pydantic "^1.9.2" while there is already pydantic 2.3 released. This dependency forces us to use an outdated pydantic version for the whole project. Would you please update vellum dependency to pydantic  >= 2.3

**Comment by noanflaherty** [comment] 2023-09-03 16:50
Hi @chapati thanks for your request. We've submitted an Issue with Fern, the company we use to auto-generate our API clients, here: https://github.com/fern-api/fern/issues/2075

Please feel free to add any additional context you'd like to that issue.

**Comment by dsinghvi** [comment] 2023-10-15 06:21
@chapati the latest version of the generated client is now Pydantic V2+ compatible!

**Comment by chapati** [comment] 2023-10-17 19:09
@dsinghvi Cool! Thanks for update and for fulfilling our request!

**Comment by noanflaherty** [comment] 2023-10-17 19:22
@dsinghvi and the Fern team are the best! Closing as resolved

**Closed as completed by noanflaherty** 2023-10-17 19:22 UTC

**Comment by IlyaTorch** [comment] 2023-10-27 14:29
Hi @noanflaherty @dsinghvi thanks for compatibility with Pydantic V2!

When updated `vellum-ai` to the latest 0.0.44 version and `pydantic` to 2.4.2 we found one issue with Vellum client's `.generate` method. 
Here is the traceback:
```python
return await client.generate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File ".../pypoetry/virtualenvs/buzz-back-yW66Rp3d-py3.11/lib/python3.11/site-packages/vellum/client.py", line 494, in generate
    return pydantic.parse_obj_as(GenerateResponse, _response.json())  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pypoetry/virtualenvs/buzz-back-yW66Rp3d-py3.11/lib/python3.11/site-packages/pydantic/v1/tools.py", line 37, in parse_obj_as
    model_type = _get_parsing_type(type_, type_name=type_name)  # type: ignore[arg-type]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pypoetry/virtualenvs/buzz-back-yW66Rp3d-py3.11/lib/python3.11/site-packages/pydantic/v1/tools.py", line 30, in _get_parsing_type
    return create_model(type_name, __root__=(type_, ...))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pypoetry/virtualenvs/buzz-back-yW66Rp3d-py3.11/lib/python3.11/site-packages/pydantic/v1/main.py", line 1026, in create_model
    return meta(__model_name, resolved_bases, namespace, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pypoetry/virtualenvs/buzz-back-yW66Rp3d-py3.11/lib/python3.11/site-packages/pydantic/v1/main.py", line 197, in __new__
    fields[ann_name] = ModelField.infer(
                       ^^^^^^^^^^^^^^^^^
  File "...pypoetry/virtualenvs/buzz-back-yW66Rp3d-py3.11/lib/python3.11/site-packages/pydantic/v1/fields.py", line 506, in infer
    return cls(
           ^^^^
  File ".../pypoetry/virtualenvs/buzz-back-yW66Rp3d-py3.11/lib/python3.11/site-packages/pydantic/v1/fields.py", line 436, in __init__
    self.prepare()
  File ".../pypoetry/virtualenvs/buzz-back-yW66Rp3d-py3.11/lib/python3.11/site-packages/pydantic/v1/fields.py", line 557, in prepare
    self.populate_validators()
  File ".../pypoetry/virtualenvs/buzz-back-yW66Rp3d-py3.11/lib/python3.11/site-packages/pydantic/v1/fields.py", line 831, in populate_validators
    *(get_validators() if get_validators else list(find_validators(self.type_, self.model_config))),
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../pypoetry/virtualenvs/buzz-back-yW66Rp3d-py3.11/lib/python3.11/site-packages/pydantic/v1/validators.py", line 765, in find_validators
    raise RuntimeError(f'no validator found for {type_}, see `arbitrary_types_allowed` in Config')
RuntimeError: no validator found for <class 'vellum.types.generate_response.GenerateResponse'>, see `arbitrary_types_allowed` in Config
```

I found out that the `GenerateResponse` model has `import pydantic` import which means pydantic v2, while its internal `GenerateResult` model has 
```
try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic
```
which imports v1 version of pydantic.

Then if we replace `import pydantic` with the
```
try:
    import pydantic.v1 as pydantic  # type: ignore
except ImportError:
    import pydantic
```
in file with `GenerateResponse` file it will work fine without any errors.

Could you please look into this issue?

**Comment by dsinghvi** [comment] 2023-11-09 16:14
> GenerateResponse

@IlyaTorch would you be up to open a small pr against vellum's client (https://github.com/vellum-ai/vellum-client-python)  with the diff that gets it to work? 

That will help us root cause the fix and update the generator

**Comment by IlyaTorch** [comment] 2023-11-14 12:44
@dsinghvi I've created [a pull request](https://github.com/vellum-ai/vellum-client-python/pull/8)

**Comment by dsinghvi** [comment] 2023-11-14 12:51
Thanks! the issue with `generate_response.py` was that it was marked by the `.fernignore`  so the generator doesn't control the file anymore. I'll see that your PR gets merged and we release a new version of the python client.

**Comment by dsinghvi** [comment] 2023-11-14 22:08
@IlyaTorch a new version of the SDK `0.1.3` should be released with the fix. I appreciate you help us tracking it down.
